services:
  - type: web
    name: career-prep-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python -m backend.app
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MODEL_NAME
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: PORT
        value: 8080
